name: Matrix Demo - 260 Combinations (exceeds 256 limit)

on:
  workflow_dispatch:

jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dimension1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
        dimension2: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - name: Log matrix combination
        run: |
          echo "Matrix combination: dimension1=${{ matrix.dimension1 }}, dimension2=${{ matrix.dimension2 }}"
          echo "This is job ${{ strategy.job-index }} out of ${{ strategy.job-total }}"
